apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  DB_HOST: "postgres.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "techsalary"
  DB_USER: "techsalary"
  IDENTITY_URL: "http://identity-service:8001"
  SALARY_URL: "http://salary-submission-service:8002"
  VOTE_URL: "http://vote-service:8003"
  SEARCH_URL: "http://search-service:8004"
  STATS_URL: "http://stats-service:8005"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: data
data:
  POSTGRES_DB: "techsalary"
  POSTGRES_USER: "techsalary"
